/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface CipherLootInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "draw"
      | "getDrawCount"
      | "getEncryptedHistory"
      | "getEncryptedResult"
      | "getLatestEncryptedResult"
      | "getProbabilityConfig"
      | "totalDraws"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "LootDrawn"): EventFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "draw", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getDrawCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedHistory",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedResult",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestEncryptedResult",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProbabilityConfig",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalDraws",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "draw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDrawCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestEncryptedResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProbabilityConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalDraws", data: BytesLike): Result;
}

export namespace LootDrawnEvent {
  export type InputTuple = [
    player: AddressLike,
    drawId: BigNumberish,
    rarityHandle: BytesLike,
    variantHandle: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    player: string,
    drawId: bigint,
    rarityHandle: string,
    variantHandle: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    player: string;
    drawId: bigint;
    rarityHandle: string;
    variantHandle: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CipherLoot extends BaseContract {
  connect(runner?: ContractRunner | null): CipherLoot;
  waitForDeployment(): Promise<this>;

  interface: CipherLootInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  draw: TypedContractMethod<[], [bigint], "nonpayable">;

  getDrawCount: TypedContractMethod<[player: AddressLike], [bigint], "view">;

  getEncryptedHistory: TypedContractMethod<
    [player: AddressLike, offset: BigNumberish, limit: BigNumberish],
    [
      [string[], string[], bigint[]] & {
        rarities: string[];
        variants: string[];
        timestamps: bigint[];
      }
    ],
    "view"
  >;

  getEncryptedResult: TypedContractMethod<
    [player: AddressLike, drawId: BigNumberish],
    [
      [string, string, bigint] & {
        rarity: string;
        variant: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getLatestEncryptedResult: TypedContractMethod<
    [player: AddressLike],
    [
      [string, string, bigint, bigint] & {
        rarity: string;
        variant: string;
        timestamp: bigint;
        drawId: bigint;
      }
    ],
    "view"
  >;

  getProbabilityConfig: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        precision: bigint;
        srCutoff: bigint;
        ssrCutoff: bigint;
      }
    ],
    "view"
  >;

  totalDraws: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "draw"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "getDrawCount"
  ): TypedContractMethod<[player: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEncryptedHistory"
  ): TypedContractMethod<
    [player: AddressLike, offset: BigNumberish, limit: BigNumberish],
    [
      [string[], string[], bigint[]] & {
        rarities: string[];
        variants: string[];
        timestamps: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEncryptedResult"
  ): TypedContractMethod<
    [player: AddressLike, drawId: BigNumberish],
    [
      [string, string, bigint] & {
        rarity: string;
        variant: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLatestEncryptedResult"
  ): TypedContractMethod<
    [player: AddressLike],
    [
      [string, string, bigint, bigint] & {
        rarity: string;
        variant: string;
        timestamp: bigint;
        drawId: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProbabilityConfig"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        precision: bigint;
        srCutoff: bigint;
        ssrCutoff: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalDraws"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "LootDrawn"
  ): TypedContractEvent<
    LootDrawnEvent.InputTuple,
    LootDrawnEvent.OutputTuple,
    LootDrawnEvent.OutputObject
  >;

  filters: {
    "LootDrawn(address,uint256,bytes32,bytes32,uint64)": TypedContractEvent<
      LootDrawnEvent.InputTuple,
      LootDrawnEvent.OutputTuple,
      LootDrawnEvent.OutputObject
    >;
    LootDrawn: TypedContractEvent<
      LootDrawnEvent.InputTuple,
      LootDrawnEvent.OutputTuple,
      LootDrawnEvent.OutputObject
    >;
  };
}
